# Lab 3 Exercise 3
## Binary Classification

We are given a dataset that consists of biological features of a person and whether or not they are a smoker.

There are *22 descriptive features* and *1 target column* in the dataset as described in the Table below. You are tasked with creating a predictive model to predict the column "SMK_stat_type_cd", which specifies smoker/non-smoker status of the person. You are expected to use classification methods that was shown in the previous exercises.



|      Column      |                                 Description                                 |
|:----------------:|:---------------------------------------------------------------------------:|
| identified_gender              | male, female                                                                |
| age              | round up to 5 years                                                         |
| height           | round up to 5 cm[cm]                                                        |
| weight           | [kg]                                                                        |
| sight_left       | eyesight(left)                                                              |
| sight_right      | eyesight(right)                                                             |
| hear_left        | hearing left, 1(normal), 2(abnormal)                                        |
| hear_right       | hearing right, 1(normal), 2(abnormal)                                       |
| SBP              | Systolic blood pressure[mmHg]                                               |
| DBP              | Diastolic blood pressure[mmHg]                                              |
| BLDS             | BLDS or FSG(fasting blood glucose)[mg/dL]                                   |
| tot_chole        | total cholesterol[mg/dL]                                                    |
| HDL_chole        | HDL cholesterol[mg/dL]                                                      |
| LDL_chole        | LDL cholesterol[mg/dL]                                                      |
| triglyceride     | triglyceride[mg/dL]                                                         |
| hemoglobin       | hemoglobin[g/dL]                                                            |
| urine_protein    | protein in urine, 1(-), 2(+/-), 3(+1), 4(+2), 5(+3), 6(+4)                  |
| serum_creatinine | serum(blood) creatinine[mg/dL]                                              |
| SGOT_AST         | SGOT(Glutamate-oxaloacetate transaminase) AST(Aspartate transaminase)[IU/L] |
| SGOT_ALT         | ALT(Alanine transaminase)[IU/L]                                             |
| gamma_GTP        | y-glutamyl transpeptidase[IU/L]                                             |
| SMK_stat_type_cd **(Target)** | Smoking state, 0(never), 1(active smoker)                      |


### The stages of this problem can be decomposed as follows:
1. Data Preparation
* Ensure data is in correct format (numerical and not string)
* Normalize the data for better convergence (optional)
* Split the data into train/test subsets

2. Model Selection
* Instanciate models and fit on training data
* Evaluate model performance on testing data
* Select model with best performance

3. Submit model
* Your model will be evaluated on data that is kept separate from training/testing data
* The predictions from your model will be uploaded to the course server where it will be evaluated

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd /content/gdrive/MyDrive/4c16-labs/code/lab-03/
!unzip -o data.zip 
!echo 'data/*' > .gitignore

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn.preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, confusion_matrix, ConfusionMatrixDisplay

In [3]:
# Data Preparation
# The data is supplied as ".csv" format
# There are 23 columns in csv file, with 22 columns being features and 1 column being the target

# The csv file can be read into as a dataframe using the pandas library
DataFrame = pd.read_csv('data/data.csv')

# Shuffle the data
DataFrame = DataFrame.sample(frac=1)

# Visualize the first 5 rows of the imported dataframe
display(DataFrame.head(6))

,identified_gender,age,height,weight,waistline,sight_left,sight_right,hear_left,hear_right,SBP,...,HDL_chole,LDL_chole,triglyceride,hemoglobin,urine_protein,serum_creatinine,SGOT_AST,SGOT_ALT,gamma_GTP,SMK_stat_type_cd
7583,Male,40,170,70,80.0,1.5,1.5,1.0,1.0,120.0,...,54.0,70.0,265.0,15.1,1.0,1.0,37.0,64.0,298.0,1.0
27382,Male,40,170,80,83.0,2.0,1.2,1.0,1.0,126.0,...,42.0,110.0,120.0,14.9,1.0,1.0,25.0,54.0,43.0,1.0
27680,Female,70,160,50,69.0,0.5,0.5,1.0,1.0,175.0,...,74.0,145.0,103.0,12.8,1.0,0.8,31.0,15.0,12.0,0.0
2950,Female,40,170,60,80.0,1.5,1.5,1.0,1.0,110.0,...,56.0,102.0,82.0,13.0,2.0,0.7,16.0,9.0,14.0,0.0
38863,Male,35,180,95,100.0,1.2,1.2,1.0,1.0,138.0,...,61.0,127.0,287.0,17.2,2.0,0.9,16.0,22.0,42.0,1.0
41536,Female,20,175,55,68.0,1.2,1.2,1.0,1.0,119.0,...,80.0,87.0,103.0,13.3,1.0,0.8,13.0,5.0,7.0,0.0

In [4]:
# The column "identified_gender" contains non-numeric data. This cannot be used as is and needs to be converted to numerical representations
# We can encode the identified gender to a numerical representation by letting "female" == 0, and "male" == 1.
# This can be done manually by using conditional statements on the dataframe, but luckily for us there is a simpler method
# We can use the built in LabelEncoder function of sklearn to do this

LabelEncoder = sklearn.preprocessing.LabelEncoder()
LabelEncoder.fit(DataFrame['identified_gender'])
DataFrame['identified_gender'] = LabelEncoder.transform(DataFrame['identified_gender'])

# Label encoder sorts the input column of data in alphabetical order, and then assigns a numerical value to each unique entry
# This results in 'female' being mapped to 0, 'male' being mapped to 1
display(DataFrame.head(6))

,identified_gender,age,height,weight,waistline,sight_left,sight_right,hear_left,hear_right,SBP,...,HDL_chole,LDL_chole,triglyceride,hemoglobin,urine_protein,serum_creatinine,SGOT_AST,SGOT_ALT,gamma_GTP,SMK_stat_type_cd
7583,1,40,170,70,80.0,1.5,1.5,1.0,1.0,120.0,...,54.0,70.0,265.0,15.1,1.0,1.0,37.0,64.0,298.0,1.0
27382,1,40,170,80,83.0,2.0,1.2,1.0,1.0,126.0,...,42.0,110.0,120.0,14.9,1.0,1.0,25.0,54.0,43.0,1.0
27680,0,70,160,50,69.0,0.5,0.5,1.0,1.0,175.0,...,74.0,145.0,103.0,12.8,1.0,0.8,31.0,15.0,12.0,0.0
2950,0,40,170,60,80.0,1.5,1.5,1.0,1.0,110.0,...,56.0,102.0,82.0,13.0,2.0,0.7,16.0,9.0,14.0,0.0
38863,1,35,180,95,100.0,1.2,1.2,1.0,1.0,138.0,...,61.0,127.0,287.0,17.2,2.0,0.9,16.0,22.0,42.0,1.0
41536,0,20,175,55,68.0,1.2,1.2,1.0,1.0,119.0,...,80.0,87.0,103.0,13.3,1.0,0.8,13.0,5.0,7.0,0.0

In [5]:
# We should now separate the input features from the target feature and store them as different variables
# We do this by slicing what columns of data we want from the dataframe
# Let's first see the columns available to us by printing DataFrame.columns
print(DataFrame.columns)

Index(['identified_gender', 'age', 'height', 'weight', 'waistline',
       'sight_left', 'sight_right', 'hear_left', 'hear_right', 'SBP', 'DBP',
       'BLDS', 'tot_chole', 'HDL_chole', 'LDL_chole', 'triglyceride',
       'hemoglobin', 'urine_protein', 'serum_creatinine', 'SGOT_AST',
       'SGOT_ALT', 'gamma_GTP', 'SMK_stat_type_cd'],
      dtype='object')

In [6]:
# The column titled "SMK_stat_type_cd" is our target, and all remaining variables are our input features.
features_columns = DataFrame.columns[:-1]
target_column = DataFrame.columns[-1:]

DataFrame_X = DataFrame[features_columns]   # Selects only Input features
DataFrame_Y = DataFrame[target_column]      # Selects only Target variable

In [7]:
# Split Data into Train/Test split
# Change the variable "test_frac" to reflect the percentage/fraction of test data in the resulting split
test_frac = 0.15

Train_X, Test_X, Train_Y, Test_Y = train_test_split(DataFrame_X.to_numpy(), DataFrame_Y.to_numpy(), test_size=test_frac)
print(f"Number of rows for Training:\t{Train_X.shape[0]}\nNumber of rows for Testing:\t{Test_X.shape[0]}")

print("Shape of training: ",Train_X.shape)
print("Shape of testing: ",Train_X.shape)

Number of rows for Training:	42500
Number of rows for Testing:	7500
Shape of training:  (42500, 22)
Shape of testing:  (42500, 22)

In [19]:
# EDIT THIS CELL
# Construct a dictionary of prediction models to compare
# Uncomment the below dictionary and insert as many prediction models as you like.
# You may have used binary classification models in previous exercises
# You may also have to import these modules/libraries to be able to use them

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import normalize


PredictionModels = {
    'Logistic Regression' : LogisticRegression(penalty='l2',solver='newton-cg'),
    'KNN Classifer'       : KNeighborsClassifier(n_neighbors=5, algorithm="kd_tree"),
    'Linear SVM'          : SGDClassifier(loss='hinge', penalty='l2'),
    'Decision Tree 5'     : DecisionTreeClassifier(max_depth=5),
    'Decision Tree 4'     : DecisionTreeClassifier(max_depth=4)
}

Train_X = normalize(Train_X)
Test_X = normalize(Test_X)


print("Fitting models, this may take a while")
for name, model in PredictionModels.items():
    print("Fitting model {}".format(name))
    model.fit(Train_X, Train_Y.ravel())
    y_pred = model.predict(Test_X)
    print("f1: ", f1_score(Test_Y, y_pred, average='binary'))

Fitting models, this may take a while
Fitting model Logistic Regression
f1:  0.6165144898769352
Fitting model KNN Classifer
f1:  0.6111413536563237
Fitting model Linear SVM
f1:  0.6255795981452859
Fitting model Decision Tree 5
f1:  0.7482483298028353
Fitting model Decision Tree 4
f1:  0.7553413654618473

In [22]:
# Select the model with best f1 score and write down the
# corresponding 'key' value from the 'PredictionModels' variable
# Eg if Logistic Regression is chosen then: chosen_model = 'Logistic Regression'
chosen_model = 'Decision Tree 4'

In [23]:
# DO NOT EDIT.
# Generate predictions using "chosen_model" and save to file

backend_features = pd.read_csv('data/validation.csv')
backend_features['identified_gender'] = LabelEncoder.transform(backend_features['identified_gender'])
backend_preds = PredictionModels[chosen_model].predict(normalize(backend_features[features_columns].to_numpy()))
np.savez_compressed('lab3_ex3_preds', lab3_model=backend_preds)

# Remember to push your changes to the git server for marking!